In [1]:

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv('Iris.csv')
df


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis = 1).values
y= le.fit_transform(df["Species"].values)


# chia dữ liệu với test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.2, random_state=42 )
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

In [4]:
len(y_train)

120

In [5]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [6]:
# tính đạo yhamf bằng pytorch
# cho y= 2x^4 + x^3 + 3x^2 + 1
#tính y'

In [7]:
import torch
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [8]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [9]:
y.grad_fn

In [10]:
y.backward()

In [11]:
x.grad

tensor(93.)

In [12]:
#btvn1
# cho y= 5x^5 + 6x^3 - 3x + 1
# cho biết độ dốc của đa thức trên ở điểm nào ?

In [13]:
import torch
x = torch.tensor(2.0, requires_grad=True)
y = 5*x**5 + 6*x**3 - 3*x + 1
y.backward()
print("Giá trị y tại x = 2:", y.item())
print("Độ dốc (dy/dx) tại x = 2:", x.grad.item())


Giá trị y tại x = 2: 203.0
Độ dốc (dy/dx) tại x = 2: 469.0


In [14]:
#btvn2
#tạo một tensor có gia trị ban đầu là 2.0
#Định nghĩa hàm số và tính gradient
#y = x^3 + 2x^2 + 5x + 1
#hãy tính dy/dx tại giá trị của x
#Dùng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

In [15]:
import torch

x = torch.tensor(2.0, requires_grad=True)

# learning rate
alpha = 0.1

print("Bắt đầu: x =", x.item())
print("-" * 60)

for i in range(10):
    # định nghĩa hàm y
    y = x**3 + 2*x**2 + 5*x + 1

    #  tính gradient dy/dx bằng backward()
    y.backward()

    # Lấy gradient hiện tại
    grad = x.grad.item()

    # In thông tin vòng lặp
    print(f"Vòng {i+1:02d}: x = {x.item(): .6f} | y = {y.item(): .6f} | dy/dx = {grad: .6f}")

    #  cập nhật x theo Gradient Descent
    # Phải dùng torch.no_grad() để PyTorch không ghi update này vào graph
    with torch.no_grad():
        x -= alpha * x.grad

    #  reset gradient về 0/None để vòng sau không bị cộng dồn
    x.grad = None

print("-" * 60)
print("Kết thúc: x =", x.item())


Bắt đầu: x = 2.0
------------------------------------------------------------
Vòng 01: x =  2.000000 | y =  27.000000 | dy/dx =  25.000000
Vòng 02: x = -0.500000 | y = -1.125000 | dy/dx =  3.750000
Vòng 03: x = -0.875000 | y = -2.513672 | dy/dx =  3.796875
Vòng 04: x = -1.254688 | y = -4.100136 | dy/dx =  4.703972
Vòng 05: x = -1.725085 | y = -6.807298 | dy/dx =  7.027413
Vòng 06: x = -2.427826 | y = -13.660884 | dy/dx =  12.971715
Vòng 07: x = -3.724998 | y = -41.560375 | dy/dx =  31.726830
Vòng 08: x = -6.897680 | y = -266.510193 | dy/dx =  120.143257
Vòng 09: x = -18.912006 | y = -6142.375000 | dy/dx =  1002.343933
Vòng 10: x = -119.146408 | y = -1663589.500000 | dy/dx =  42116.011719
------------------------------------------------------------
Kết thúc: x = -4330.74755859375


In [16]:
#btvn3
#Tạo một tập dữ liệu giả lập với x là số giờ học( ngẫu nhiên từ 1 - 10)
#và y là số điểm được tính theo công thức y = 3x + 5 + noise
#Với noise là một giá trị ngẫu nhiên nhỏ
#1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad= true
#2. tính MSE
#3. Tính gradient
#4. Cập nhật tham số w và b bằng gradient Descent với Learning rate alpha = 0.01
#5. Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình

In [32]:
import torch

torch.manual_seed(0)  # cố định seed để dễ tái lập kết quả
# tạo dữ liệu: x là số giờ học từ 1–10
x = torch.randint(1, 11, (100, 1)).float()
# noise nhỏ
noise = torch.randn_like(x) * 0.5
# y = 3x + 5 + noise
y = 3 * x + 5 + noise
# khởi tạo w và b ngẫu nhiên, cho phép tính gradient
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
alpha = 0.01   # learning rate
epochs = 100   # số vòng lặp
for epoch in range(epochs):
    y_pred = w * x + b                 # dự đoán
    loss = torch.mean((y_pred - y)**2) # tính MSE
    loss.backward()                    # tính gradient
    with torch.no_grad():              # cập nhật tham số
        w -= alpha * w.grad
        b -= alpha * b.grad
    w.grad.zero_()                     # reset gradient
    b.grad.zero_()
    if (epoch + 1) % 10 == 0:           # in để quan sát hội tụ
        print(f"Epoch {epoch+1}: Loss={loss.item():.4f}, w={w.item():.4f}, b={b.item():.4f}")
print("w ≈", w.item())
print("b ≈", b.item())


Epoch 10: Loss=5.2748, w=3.6777, b=0.1325
Epoch 20: Loss=4.8557, w=3.6497, b=0.3346
Epoch 30: Loss=4.4713, w=3.6229, b=0.5282
Epoch 40: Loss=4.1186, w=3.5971, b=0.7136
Epoch 50: Loss=3.7951, w=3.5725, b=0.8911
Epoch 60: Loss=3.4984, w=3.5490, b=1.0612
Epoch 70: Loss=3.2261, w=3.5264, b=1.2241
Epoch 80: Loss=2.9764, w=3.5047, b=1.3801
Epoch 90: Loss=2.7474, w=3.4840, b=1.5295
Epoch 100: Loss=2.5373, w=3.4642, b=1.6726
w ≈ 3.4641854763031006
b ≈ 1.6726096868515015


In [18]:
import torch
import numpy as np

In [19]:
torch.__version__

'2.7.1+cu118'

In [20]:
# Chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [21]:
x = torch.from_numpy(arr)
print(x)


tensor([1, 2, 3, 4, 5])


In [22]:
print(x.dtype)

torch.int64


In [23]:
print(x.type())

torch.LongTensor


In [24]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [25]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [26]:
#copying and sharing
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)


tensor([0, 1, 2, 3, 4])


In [27]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4])


In [28]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [29]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


In [30]:
# BTVN 4 : Giải thích lý do tại sao cho 2 trường hợp trên

Ở trường hợp dùng torch.from_numpy(), tensor và mảng NumPy dùng chung vùng nhớ nên khi thay đổi giá trị của mảng NumPy thì giá trị trong tensor cũng thay đổi theo.
Còn với torch.tensor(), PyTorch tạo một bản sao dữ liệu mới nên tensor và mảng NumPy là độc lập, vì vậy thay đổi mảng NumPy không làm ảnh hưởng đến tensor.

In [31]:
# BTVN 5: bạn hãy giúp thầy về nhà tạo tensor với:
# Empyty
# Zeros
# Ones
# Random
# Reshape với view và view as




In [33]:
import torch

# tạo tensor rỗng 
a = torch.empty(2, 3)
print("Empty tensor:\n", a)

# tạo tensor toàn số 0
b = torch.zeros(2, 3)
print("\nZeros tensor:\n", b)

# tạo tensor toàn số 1
c = torch.ones(2, 3)
print("\nOnes tensor:\n", c)

# tạo tensor ngẫu nhiên
d = torch.rand(2, 3)
print("\nRandom tensor:\n", d)

# reshape bằng view
e = torch.arange(0, 12)
e_view = e.view(3, 4)
print("\nView reshape:\n", e_view)

# reshape bằng view_as
f = torch.zeros(3, 4)
e_view_as = e.view_as(f)
print("\nView as reshape:\n", e_view_as)


Empty tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random tensor:
 tensor([[0.4641, 0.9946, 0.6806],
        [0.5142, 0.0667, 0.7477]])

View reshape:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

View as reshape:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
