# DEEPLEARNING

## TUẦN 2 : NUMPY, PANDAS, Matplotlib


# NUMPY

In [1]:
# NUMPY là thư viện kiểu list
# vì:
# +numpy nhanh
# +có nhiều hàm tích hợp dễ sử dụng cho AI

# để sử dụng thì : pip install numpy
import numpy as np

In [3]:
#thử tạo 1 list
python_list= [1,2,3]
# chuyển đổi danh sách trên thành numpy list 
numpy_list= np.array(python_list)
type(numpy_list
     )

numpy.ndarray

In [4]:
#list trong python có thể hỗ trợ nhiều loại dữ liệu trong list  
my_list = [1, "chào", True, 2.0]

In [8]:
my_list=[1,2,3,4.5]
np_list= np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [9]:
# chuyển đổi kiểu dữ liệu ?
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [10]:
#accessing và indexing
x= np.array([1,2,3,4,5,6,7,8])# x = np.array (range(1,9))

In [12]:
#lấy số 4
x[3]

np.int64(4)

In [13]:
#lấy nhiều hơn 1 phần tử 
#công thức [start: end: step]
x[0:3]

array([1, 2, 3])

In [ ]:
# lấy từ 3 đến 8 theo 3 cách 
#cách 1
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [16]:
# cách 2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [17]:
# lấy số 3 với 5
x[2],x[4]

(np.int64(3), np.int64(5))

In [19]:
# đặt danh sách về các index muốn truy cập 
x[[2,4]]

array([3, 5])

In [20]:
data= [[1,2],[3,4],[5,6]]
np_list=np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
#lấy số 2 
np_list[0,1]

np.int64(2)

In [ ]:
#lấy số 6 
np_list[2,1 ]

np.int64(6)

In [ ]:
#lấy [3,4][5,6]
#c
np_list[1:,:]

array([[3, 4],
       [5, 6]])

In [24]:
#c2
np_list[[1,2],:]


array([[3, 4],
       [5, 6]])

In [27]:
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [48]:
# lấy 1,3,5
np_list[0:,0]


array([1, 3, 5])

In [51]:
# lấy 1 và 5 theo 2 cách 
#c1
np_list[[0,2],0]


array([1, 5])

In [52]:
#c2 bước nhảy
np_list[0::2,0  ]

array([1, 5])

In [17]:
x=[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list=np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
# lấy 2,6 ,10, 14 
np_list[:,1]

array([ 2,  6, 10, 14])

In [18]:
# lấy 7 ,11
np_list[[1,2],2]

array([ 7, 11])

In [57]:
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [ ]:
#lấy 16,15,14,13
#c1
np_list[3,::-1]

array([16, 15, 14, 13])

In [ ]:
#c2
np_list[[3,3,3,3],[3,2,1,0]]

array([16, 15, 14, 13])

In [ ]:
#c3
np_list[-1,::-1]

array([16, 15, 14, 13])

In [ ]:
#### BTVN 1:cho ma trận = [[99,99,99]
#                          [99,99,99]
#                          [99,99,99]]
#hãy tượng tượng  ô 99 trống
#giả sử 1 là x
# giả sử 0 là o

# lấy đầu vào từ phía X và phía O luân phiên
# nếu đầu vào từ ohias X là (0,0)

# ma trận sẽ trở thành 
#[[x,99,99]
# [99,99,99]
# [99,99,99]]

# nếu đầu vào từ phía o cũng là (0,0)
# thông báo nhập lại 
# nếu không thi điền vào ma trận 

# Thử thách : nếu người đầu tiên có 3 phần tử liên tiếp hãy dừng trò chơi 

In [5]:
import numpy as np
import pandas as pd
board = np.full((3, 3), 99)
def print_board():
    print(pd.DataFrame(board))
    print()
def check_win(player):
    for i in range(3):
        if np.all(board[i] == player):
            return True
    for j in range(3):
        if np.all(board[:, j] == player):
            return True
    if np.all(np.diag(board) == player):
        return True
    if np.all(np.diag(np.fliplr(board)) == player):
        return True

    return False
player = 1 
while True:
    print_board()
    name = "X" if player == 1 else "O"
    x = int(input(f"Lượt {name}, nhập hàng (0-2): "))
    y = int(input(f"Lượt {name}, nhập cột (0-2): "))

    if board[x, y] != 99:
        print("Ô đã được đánh, nhập lại!")
        continue
    board[x, y] = player

    if check_win(player):
        print_board()
        print(f"{name} thắng!")
        break
    player = 0 if player == 1 else 1


    0   1   2
0  99  99  99
1  99  99  99
2  99  99  99

    0   1   2
0   1  99  99
1  99  99  99
2  99  99  99

    0   1   2
0   1  99  99
1  99   0  99
2  99  99  99

    0   1   2
0   1  99  99
1   1   0  99
2  99  99  99

    0   1   2
0   1  99  99
1   1   0   0
2  99  99  99

   0   1   2
0  1  99  99
1  1   0   0
2  1  99  99

X thắng!


In [25]:
# BTVN2:
import numpy as np
y = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
# lấy 4 5 6
# lấy 2, 5
# lấy 3 4
# lấy 9 6 3

np_list= np.array(y)
np_list[1, ::1 ]


array([4, 5, 6])

In [14]:
np_list[[0,1], [1,1]]#lấy 4,5,6

array([2, 5])

In [27]:
np_list[::-1, -1]

array([9, 6, 3])

In [29]:
np_list[[0,1], 1]

array([2, 5])

In [ ]:
# BTVN 3:
# CHO X=[1,2,3,4,5,6,7,8,9,10]
# 1.xuất ra các giá trị chẵn theo sử dung if
# 2.xuất ra các giá trị chẵn theo sử dung list comprehension


In [6]:
# 1.xuất ra các giá trị chẵn theo sử dung if
X = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("Các giá trị chẵn (dùng if):")
for i in X:
    if i % 2 == 0:
        print(i)

Các giá trị chẵn (dùng if):
2
4
6
8
10


In [7]:
# 2.xuất ra các giá trị chẵn theo sử dung list comprehension
X = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
chan_list = [i for i in X if i % 2 == 0]
print("Các giá trị chẵn (dùng list comprehension):")
print(chan_list)

Các giá trị chẵn (dùng list comprehension):
[2, 4, 6, 8, 10]


In [62]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# lấy giá trị chẵn
np_x[np_x %2==0]

array([0, 2, 4, 6, 8])

In [ ]:

np_x %2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [67]:
idx= [True, False,  True, False,  True, False,  True, False,  True,
       False]
np_x[idx]

array([0, 2, 4, 6, 8])

In [68]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
cond1 = np_x %2 !=0
cond2 = np_x <5
cond3 = np_x >0
 
np_x[cond1 & cond2| cond3]



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# BTVN
# tạo  1 mảng có kích thước 150x5 . Giả sử mảng này chứa 150 mẫu dữ liệu của sinh viên bao gồm
# chiều cao cân nặng , tuổi , lương , điểm trung bình 
# tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là X và cột cuối cùng thành y 
# tách x thành x_train và x_test trong đó x_train chứa 70% dữ liệu 
# tách y thành y_train và y _test trong đó y train chứa 70% dữ liệu 
# tạo 10 tập dữ liệu không chồng chéo nhau 

In [8]:
import numpy as np
from sklearn.model_selection import train_test_split, KFold
data = np.random.rand(150, 5)

#  Tách mảng thành X (4 cột đầu) và y (cột cuối)
X = data[:, :4]  # Lấy tất cả hàng, từ cột 0 đến cột 3
y = data[:, 4]   # Lấy tất cả hàng, chỉ lấy cột 4

#  Tách X, y thành tập train (70%) và test (30%)
# Sử dụng shuffle=True để dữ liệu được xáo trộn ngẫu nhiên trước khi chia
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Tạo 10 tập dữ liệu không chồng chéo nhau (K-Fold Cross Validation)
kf = KFold(n_splits=10)

print(f"Kích thước X_train: {X_train.shape}")
print(f"Kích thước X_test: {X_test.shape}")
print("-" * 30)
for i, (train_index, val_index) in enumerate(kf.split(X)):
    print(f"Tập thứ {i+1}: Index kiểm tra từ {val_index[0]} đến {val_index[-1]}")

Kích thước X_train: (105, 4)
Kích thước X_test: (45, 4)
------------------------------
Tập thứ 1: Index kiểm tra từ 0 đến 14
Tập thứ 2: Index kiểm tra từ 15 đến 29
Tập thứ 3: Index kiểm tra từ 30 đến 44
Tập thứ 4: Index kiểm tra từ 45 đến 59
Tập thứ 5: Index kiểm tra từ 60 đến 74
Tập thứ 6: Index kiểm tra từ 75 đến 89
Tập thứ 7: Index kiểm tra từ 90 đến 104
Tập thứ 8: Index kiểm tra từ 105 đến 119
Tập thứ 9: Index kiểm tra từ 120 đến 134
Tập thứ 10: Index kiểm tra từ 135 đến 149
